export const uiStrings = {
  en: {
    appTitle: 'Toolkit for Disability Wellbeing',
    skipToMain: 'Skip to main content',
    skipToPageContent: 'Skip to page content',
    skipToNav: 'Skip to main navigation',
    skipToFooter: 'Skip to footer',
    backToTop: '↑ Back to top',
    accessibility: 'Accessibility',
    language: 'Language',
    nav: {
      about: 'About',
      resources: 'Resources',
      stories: 'Stories',
      map: 'Map',
      advocacy: 'Advocacy',
    },
    home: {
      title: 'Toolkit for Disability Wellbeing',
      cards: {
        resourcesTitle: 'Immediate Resources',
        resourcesBody: 'Find healthcare, legal, housing, and community support.',
        storiesTitle: 'Community Stories',
        storiesBody: 'Read lived experiences from disabled residents.',
        mapTitle: 'Accessibility Map',
        mapBody: 'Explore accessible and inaccessible spaces in Bethlehem.',
        policyTitle: 'Policy & Service Gaps',
        policyBody: 'Learn about local accessibility challenges and recommendations.',
        activismTitle: 'Disability Activism',
        activismBody: 'Explore movements and discussions around disability justice.',
        reportTitle: 'Report a Website Issue',
        reportBody: 'Report a bug or issue with the website, content, or listings.',
        submitTitle: 'Submit a Resource or Story',
        submitBody: 'Share a resource or community story for review.',
        aboutTitle: 'About the Toolkit',
        aboutBody: 'Learn about the project and collaborators.',
        accessibilityStatementTitle: 'Accessibility Statement',
        accessibilityStatementBody:
          'Read how this site supports accessibility and aligns with WCAG guidelines.',
      },
      cta: {
        text: 'Know a resource or have a story? Share it with the community.',
        button: 'Submit a Resource or Story',
      },
      reportCta: {
        text: 'Noticed an inaccessible place or barrier? Report it on the Accessibility Map.',
        button: 'Report an Inaccessible Place',
      },
    },
    pages: {
      immediateResources: {
        title: 'Immediate Resources',
        subtitle: 'Healthcare, legal, and community support in Bethlehem.',
        skipNavAria: 'Skip links for Immediate Resources',
        skipToSearch: 'Skip to search',
        skipToFilters: 'Skip to filters',
        skipToResults: 'Skip to results',
        backHome: '← Back to Home',
        loading: 'Loading resources...',
        searchLabel: 'Search resources',
        searchFilterAria: 'Search and filter resources',
        searchInputAria: 'Search resources by name, description, or category',
        searchPlaceholder: 'Search by name, description, or category…',
        filterLegend: 'Filter by category',
        filterGroupAria: 'Filter by category',
        showAllAria: 'Show all categories',
        filterByAria: 'Filter by {{category}}',
        filterAll: 'All',
        resultsNone: 'No resources match your search.',
        resultsCount: 'Showing {{count}} {{item}}.',
        resultsItemSingular: 'resource',
        resultsItemPlural: 'resources',
        viewDetails: 'View details →',
        cardAriaLabel: '{{title}}. Category: {{category}}. View details.',
        communityFeedbackAria: 'Community feedback',
        foundHelpful: '{{count}} found this helpful',
        didNot: '{{count}} did not',
      },
      communityStories: {
        title: 'Community Stories',
        subtitle:
          'Lived experiences from disabled residents and their communities in Bethlehem.',
        backHome: '← Back to Home',
        loading: 'Loading stories...',
        empty: 'Community stories are coming soon. Check back soon.',
        readFull: 'Read Full Story →',
      },
      policyGaps: {
        loading: 'Loading Policy & Service Gaps...',
        backHome: '← Back to Home',
      },
      disabilityActivism: {
        loading: 'Loading Disability Activism...',
        backHome: '← Back to Home',
        furtherReading: 'Further Reading',
        sources: 'Sources',
      },
      resourceDetail: {
        backToResources: '← Back to Immediate Resources',
        visitWebsite: 'Visit Website ↗',
        viewOnMap: 'View on map ↗',
        aboutThisResource: 'About this resource',
        photos: 'Photos',
        contact: 'Contact',
        lightboxLabel: 'View photo',
        lightboxClose: 'Close',
        lightboxPrev: 'Previous photo',
        lightboxNext: 'Next photo',
        viewPhotoNumber: 'View photo {{n}}',
        photoNumber: 'Photo {{n}}',
      },
      reportIssue: {
        backHome: '← Back to Home',
        title: 'Report a Website Issue',
        subtitle: 'Use this form to report issues with the website, content, or listings.',
        locationRedirectTitle: 'Reporting an inaccessible place or physical barrier?',
        locationRedirectBody: 'Use the Accessibility Map report flow so we can review and map the location accurately.',
        locationRedirectButton: 'Report on the Accessibility Map',
        subjectLabel: 'Issue title',
        detailsLabel: 'What happened?',
        photoLabel: 'Photo (optional)',
        pageUrlLabel: 'Page URL (optional)',
        locationDescriptionLabel: 'Where did this happen? (page or section, optional)',
        nameLabel: 'Your name (optional)',
        emailLabel: 'Email (optional)',
        submitButton: 'Submit report',
        submitting: 'Submitting...',
        successMessage: 'Thank you. Your report was submitted for review.',
        errorMessage: 'Could not submit the report. Please try again.',
      },
      accessibilityStatement: {
        feedbackText: 'Need feedback or support with this website accessibility?',
        feedbackLinkLabel: 'Report a Website Issue',
      },
      submitForm: {
        backHome: '← Back to Home',
        title: 'Submit a Resource or Community Story',
        subtitle:
          'Your submission will be reviewed by the Toolkit team before being added to the site.',
        skipNavAria: 'Skip links for submit form',
        skipToType: 'Skip to submission type',
        skipToContact: 'Skip to contact details',
        skipToDetails: 'Skip to resource or story details',
        skipToSend: 'Skip to send submission',
        shareLegend: 'What would you like to share?',
        shareResourceTitle: 'Submit a resource',
        shareResourceDescription:
          'Share a service, organization, or support (healthcare, legal aid, housing, etc.)',
        shareStoryTitle: 'Submit a community story',
        shareStoryDescription:
          'Share a lived experience from the Bethlehem disability community',
        contactLegend: 'Your contact (optional)',
        nameLabel: 'Your name',
        emailLabel: 'Email address',
        resourceLegend: 'Resource details',
        resourceNameLabel: 'Resource name',
        websiteLinkLabel: 'Website link',
        categoryLabel: 'Category',
        categorySelectPlaceholder: 'Select a category (required)',
        categoryHelpText: 'Choose one category to help us route your submission.',
        categoryKeyboardHelpText:
          'Keyboard tip: when focused on Category, use Arrow keys to move options. Press Enter or Space to open the list in supported browsers.',
        categoryRequiredError: 'Please choose a category before sending.',
        categories: {
          legalAid: 'Legal Aid',
          communityOrganizations: 'Community Organizations',
          mutualAidSupport: 'Mutual Aid Support',
          collaborativeSupport: 'Collaborative Support',
          employmentSupport: 'Employment Support',
          foodAccessAndHousingSupport: 'Food Access and Housing Support',
          healthcareSupport: 'Healthcare Support',
          transportationServices: 'Transportation Services',
          multilingualSupport: 'Multilingual Support',
          mentalHealthSupport: 'Mental Health Support',
        },
        descriptionLabel: 'Description',
        resourceContactEmailLabel: 'Contact email',
        resourceContactPhoneLabel: 'Contact phone',
        streetAddressLabel: 'Street address',
        cityLabel: 'City',
        stateLabel: 'State',
        zipCodeLabel: 'ZIP code',
        storyLegend: 'Story details',
        storyTitleLabel: 'Story title',
        storyPersonNameLabel: 'Name or pseudonym',
        storyLocationLabel: 'Location',
        storySummaryLabel: 'Short summary',
        storyBodyLabel: 'Full story',
        sending: 'Sending...',
        sendButton: 'Send submission',
        successMessage: 'Thank you. Your submission has been received.',
        errorMessage: 'Something went wrong. Please try again later.',
      },
      accessibilityMap: {
        title: 'Accessibility Map',
        subtitle: 'Explore disability resources and services in Bethlehem.',
        backHome: '← Back to Home',
        loading: 'Loading map...',
        mapAriaLabel: 'Interactive map of resources and accessibility issues',
        viewDetails: 'View details',
        showingResource: 'Showing map location for: {{title}}.',
        clearSelection: 'Show all resources',
        showReports: 'Show inaccessible location reports',
        showResources: 'Show immediate resources',
        inaccessibleLocationsTitle: 'Inaccessible Locations',
        inaccessibleLocationsDescription: 'This map shows locations that have been reported as inaccessible. Help us improve accessibility by reporting issues you encounter.',
        reportInaccessibleLocation: 'Report Inaccessible Location',
        cancel: 'Cancel',
        reportAnother: 'Report another inaccessible location',
        reportDetails: 'Report Details',
        subjectLabel: 'Subject',
        detailsLabel: 'Details',
        photoLabel: 'Photo (optional)',
        locationLegend: 'Location',
        enterAddress: 'Enter address',
        useCurrentLocation: 'Use current location',
        streetLabel: 'Street',
        cityLabel: 'City',
        stateLabel: 'State',
        zipCodeLabel: 'ZIP Code',
        contactLegend: 'Contact Information (Optional)',
        nameLabel: 'Name',
        emailLabel: 'Email',
        submitReport: 'Submit Report',
        submitting: 'Submitting...',
        successMessage: 'Thank you for your submission. We will review this report and publish it once it has been verified.',
        errorMessage: 'Error submitting report. Please try again.',
        accessibleResourcesTitle: 'Accessible Resources',
        accessibleResourcesDescription: 'This map shows locations of resources that can help with disability support and accessibility.',
        getCurrentLocation: 'Get Current Location',
        coordinatesFound: 'Coordinates found:',
        nearbyAddress: 'Nearby address:',
        placePinOnMap: 'Place pin on map',
        pinInstructions: 'Click the map above to place a pin. You can drag the pin to fine-tune its location.',
      },
    },
    accessibilityPanel: {
      title: 'Accessibility Options',
      close: 'Close accessibility options',
      textSize: 'Text size',
      textSizeSmaller: 'Smaller',
      textSizeDefault: 'Default',
      textSizeLarge: 'Large',
      textSizeXLarge: 'Extra Large',
      colorContrast: 'Color contrast',
      contrastDefault: 'Default',
      contrastHigh: 'High Contrast',
      readingFont: 'Reading font',
      fontDefault: 'Default',
      fontDyslexia: 'Dyslexia-Friendly',
      dyslexiaHint:
        'Dyslexia-friendly mode uses a clean sans-serif font with wider letter and word spacing.',
      motionLayout: 'Motion & layout',
      reduceAnimations: 'Reduce animations',
      increaseSpacing: 'Increase spacing',
      underlineLinks: 'Underline all links',
      reset: 'Reset all accessibility settings',
    },
    breadcrumb: {
      home: 'Home',
      resources: 'Immediate Resources',
      resource: 'Resource',
      communityStories: 'Community Stories',
      story: 'Story',
      map: 'Accessibility Map',
      policyGaps: 'Policy & Service Gaps',
      disabilityActivism: 'Disability Activism',
      submit: 'Submit a Resource or Story',
      accessibilityStatement: 'Accessibility Statement',
      about: 'About',
      privacyPolicy: 'Privacy Policy',
      sitemap: 'Site Map',
      disclaimers: 'Disclaimers',
    },
    wasThisHelpful: {
      question: 'Was this helpful?',
      yes: 'Yes',
      no: 'No',
      thanks: 'Thank you for your feedback.',
      foundHelpful: '{{count}} found this helpful',
      didNot: '{{count}} did not',
      improveLabel: 'How could this resource be improved? (1–2 sentences required)',
      improvePlaceholder: 'e.g., Add more contact options or clarify the eligibility requirements…',
      cancel: 'Cancel',
      submitFeedback: 'Submit feedback',
      submitting: 'Submitting…',
      improveError: 'Please provide 1–2 sentences on how this resource could improve (at least 20 characters).',
      saveError: 'Failed to save your feedback. Check that VITE_SANITY_TOKEN is set in .env with write permissions.',
      rateAriaLabel: 'Rate this resource',
      yesNoAriaLabel: 'Yes or No',
    },
    comments: {
      title: 'Comments',
      commentLabelResource: 'Add a comment about this resource',
      commentLabelStory: 'Add a comment about this story',
      placeholderResource: 'Share your experience with this resource, ask questions, or help others… (anonymous)',
      placeholderStory: 'Share your thoughts... (anonymous)',
      placeholderInline: 'Add a comment...',
      charCount: '{{count}} of {{max}} characters',
      postComment: 'Post Comment',
      posting: 'Posting...',
      loading: 'Loading comments...',
      noComments: 'No comments yet. Be the first to share your thoughts!',
      noCommentsInline: 'Be the first to comment',
      anonymous: 'Anonymous',
      flag: 'Flag comment',
      flagged: 'Comment flagged',
      flagCount: '{{count}} flag(s)',
      commentEmpty: 'Comment cannot be empty',
      loadError: 'Failed to load comments',
      postError: 'Failed to post comment. Please try again.',
      postErrorShort: 'Failed to post comment',
      flagError: 'Failed to flag comment',
      alreadyFlagged: 'You have already flagged this comment',
      postSuccess: 'Comment posted successfully!',
      flagSuccess: 'Comment flagged. Thank you for helping keep the community safe.',
      rateLimitExceeded: 'You can submit at most {{max}} comments per minute. Please wait before posting again.',
      flagLimitExceeded: 'You have reached your daily flag limit. Please try again tomorrow.',
      commentsOnPassage: 'Comments on this passage',
      closeComments: 'Close comments',
      commentOnParagraph: 'Comment on this paragraph',
      paragraph: 'Paragraph:',
      post: 'Post',
      inlineCommentsAria: '{{count}} inline comments',
      addInlineCommentAria: 'Add inline comment',
    },
    footer: {
      navigation: 'Navigation',
      information: 'Information',
      contactUs: 'Contact Us',
      emailLabel: 'Email',
      phoneLabel: 'Phone',
      addressLabel: 'Address',
      aboutBody:
        'The Toolkit for Disability Wellbeing is a community-driven initiative supporting disabled residents in Bethlehem, PA through accessible resources and shared experiences.',
      learnMore: 'Learn more about the project',
      copyright:
        '© {{year}} Toolkit for Disability Wellbeing. All rights reserved. Created in collaboration with Lehigh University and the Bethlehem community.',
    },
  },
  es: {
    appTitle: 'Kit para el bienestar de la discapacidad',
    skipToMain: 'Saltar al contenido principal',
    skipToPageContent: 'Saltar al contenido de la pagina',
    skipToNav: 'Saltar a la navegación principal',
    skipToFooter: 'Saltar al pie de página',
    backToTop: '↑ Volver arriba',
    accessibility: 'Accesibilidad',
    language: 'Idioma',
    nav: {
      about: 'Acerca de',
      resources: 'Recursos',
      stories: 'Historias',
      map: 'Mapa',
      advocacy: 'Incidencia',
    },
    home: {
      title: 'Kit para el bienestar de la discapacidad',
      cards: {
        resourcesTitle: 'Recursos inmediatos',
        resourcesBody:
          'Encuentra apoyo de salud, legal, vivienda y apoyo comunitario.',
        storiesTitle: 'Historias de la comunidad',
        storiesBody: 'Lee experiencias vividas de residentes con discapacidad.',
        mapTitle: 'Mapa de accesibilidad',
        mapBody: 'Explora espacios accesibles e inaccesibles en Bethlehem.',
        policyTitle: 'Brechas de políticas y servicios',
        policyBody:
          'Conoce desafíos locales de accesibilidad y recomendaciones.',
        activismTitle: 'Activismo por la discapacidad',
        activismBody:
          'Explora movimientos y conversaciones sobre justicia para la discapacidad.',
        reportTitle: 'Reportar un problema del sitio web',
        reportBody: 'Reporta un error o problema del sitio web, contenido o listados.',
        submitTitle: 'Enviar un recurso o historia',
        submitBody: 'Comparte un recurso o una historia para revisión.',
        aboutTitle: 'Acerca del kit',
        aboutBody: 'Conoce el proyecto y sus colaboradores.',
        accessibilityStatementTitle: 'Declaracion de accesibilidad',
        accessibilityStatementBody:
          'Conoce como este sitio apoya la accesibilidad y se alinea con las pautas WCAG.',
      },
      cta: {
        text:
          '¿Sabes algo que nosotros no? Este kit crece con aportes de la comunidad.',
        button: 'Contribuir al kit',
      },
      reportCta: {
        text: '¿Notaste un lugar inaccesible o una barrera? Repórtalo en el Mapa de Accesibilidad.',
        button: 'Reportar un problema de accesibilidad',
      },
    },
    pages: {
      immediateResources: {
        title: 'Recursos inmediatos',
        subtitle: 'Apoyo de salud, legal y comunitario en Bethlehem.',
        skipNavAria: 'Enlaces para saltar en Recursos inmediatos',
        skipToSearch: 'Saltar a la búsqueda',
        skipToFilters: 'Saltar a los filtros',
        skipToResults: 'Saltar a los resultados',
        backHome: '← Volver al inicio',
        loading: 'Cargando recursos...',
        searchLabel: 'Buscar recursos',
        searchFilterAria: 'Buscar y filtrar recursos',
        searchInputAria: 'Buscar recursos por nombre, descripción o categoría',
        searchPlaceholder: 'Buscar por nombre, descripción o categoría…',
        filterLegend: 'Filtrar por categoría',
        filterGroupAria: 'Filtrar por categoría',
        showAllAria: 'Mostrar todas las categorías',
        filterByAria: 'Filtrar por {{category}}',
        filterAll: 'Todos',
        resultsNone: 'Ningún recurso coincide con tu búsqueda.',
        resultsCount: 'Mostrando {{count}} {{item}}.',
        resultsItemSingular: 'recurso',
        resultsItemPlural: 'recursos',
        viewDetails: 'Ver detalles →',
        cardAriaLabel: '{{title}}. Categoría: {{category}}. Ver detalles.',
        communityFeedbackAria: 'Comentarios de la comunidad',
        foundHelpful: '{{count}} encontraron esto útil',
        didNot: '{{count}} no',
      },
      communityStories: {
        title: 'Historias de la comunidad',
        subtitle:
          'Experiencias vividas de residentes con discapacidad y sus comunidades en Bethlehem.',
        backHome: '← Volver al inicio',
        loading: 'Cargando historias...',
        empty: 'Las historias de la comunidad llegarán pronto. Vuelve pronto.',
        readFull: 'Leer historia completa →',
      },
      policyGaps: {
        loading: 'Cargando brechas de políticas y servicios...',
        backHome: '← Volver al inicio',
      },
      disabilityActivism: {
        loading: 'Cargando activismo por la discapacidad...',
        backHome: '← Volver al inicio',
        furtherReading: 'Lecturas recomendadas',
        sources: 'Fuentes',
      },
      resourceDetail: {
        backToResources: '← Volver a recursos inmediatos',
        visitWebsite: 'Visitar sitio web ↗',
        viewOnMap: 'Ver en el mapa ↗',
        aboutThisResource: 'Acerca de este recurso',
        photos: 'Fotos',
        contact: 'Contacto',
        lightboxLabel: 'Ver foto',
        lightboxClose: 'Cerrar',
        lightboxPrev: 'Foto anterior',
        lightboxNext: 'Siguiente foto',
        viewPhotoNumber: 'Ver foto {{n}}',
        photoNumber: 'Foto {{n}}',
      },
      reportIssue: {
        backHome: '← Volver al inicio',
        title: 'Reportar un problema del sitio web',
        subtitle: 'Usa este formulario para reportar problemas del sitio web, contenido o listados.',
        locationRedirectTitle: '¿Vas a reportar un lugar inaccesible o una barrera fisica?',
        locationRedirectBody: 'Usa el flujo del Mapa de Accesibilidad para que podamos revisar y ubicar la localizacion correctamente.',
        locationRedirectButton: 'Reportar en el Mapa de Accesibilidad',
        subjectLabel: 'Título del problema',
        detailsLabel: '¿Qué pasó?',
        photoLabel: 'Foto (opcional)',
        pageUrlLabel: 'URL de la página (opcional)',
        locationDescriptionLabel: '¿Dónde ocurrió esto? (página o sección, opcional)',
        nameLabel: 'Tu nombre (opcional)',
        emailLabel: 'Correo electrónico (opcional)',
        submitButton: 'Enviar reporte',
        submitting: 'Enviando...',
        successMessage: 'Gracias. Tu reporte fue enviado para revisión.',
        errorMessage: 'No se pudo enviar el reporte. Inténtalo de nuevo.',
      },
      accessibilityStatement: {
        feedbackText: '¿Necesitas enviar comentarios o recibir apoyo sobre la accesibilidad de este sitio web?',
        feedbackLinkLabel: 'Reportar un problema del sitio web',
      },
      submitForm: {
        backHome: '← Volver al inicio',
        title: 'Enviar un recurso o historia de la comunidad',
        subtitle:
          'Tu envío será revisado por el equipo del Kit antes de agregarse al sitio.',
        skipNavAria: 'Enlaces para saltar en el formulario',
        skipToType: 'Saltar al tipo de envio',
        skipToContact: 'Saltar a los datos de contacto',
        skipToDetails: 'Saltar a los detalles del recurso o historia',
        skipToSend: 'Saltar a enviar el formulario',
        shareLegend: '¿Qué te gustaría compartir?',
        shareResourceTitle: 'Enviar un recurso',
        shareResourceDescription:
          'Comparte un servicio, organización o apoyo (salud, asistencia legal, vivienda, etc.)',
        shareStoryTitle: 'Enviar una historia de la comunidad',
        shareStoryDescription:
          'Comparte una experiencia vivida de la comunidad de discapacidad de Bethlehem',
        contactLegend: 'Tu información de contacto (opcional)',
        nameLabel: 'Tu nombre',
        emailLabel: 'Correo electrónico',
        resourceLegend: 'Detalles del recurso',
        resourceNameLabel: 'Nombre del recurso',
        websiteLinkLabel: 'Enlace del sitio web',
        categoryLabel: 'Categoría',
        categorySelectPlaceholder: 'Selecciona una categoría (obligatoria)',
        categoryHelpText: 'Elige una categoría para ayudarnos a clasificar tu envío.',
        categoryKeyboardHelpText:
          'Consejo de teclado: cuando el foco esté en Categoría, usa las flechas para recorrer opciones. Presiona Enter o Espacio para abrir la lista en navegadores compatibles.',
        categoryRequiredError: 'Elige una categoría antes de enviar.',
        categories: {
          legalAid: 'Asistencia legal',
          communityOrganizations: 'Organizaciones comunitarias',
          mutualAidSupport: 'Apoyo de ayuda mutua',
          collaborativeSupport: 'Apoyo colaborativo',
          employmentSupport: 'Apoyo para empleo',
          foodAccessAndHousingSupport: 'Acceso a alimentos y apoyo de vivienda',
          healthcareSupport: 'Apoyo de salud',
          transportationServices: 'Servicios de transporte',
          multilingualSupport: 'Apoyo multilingüe',
          mentalHealthSupport: 'Apoyo de salud mental',
        },
        descriptionLabel: 'Descripción',
        resourceContactEmailLabel: 'Correo de contacto',
        resourceContactPhoneLabel: 'Teléfono de contacto',
        streetAddressLabel: 'Dirección (calle)',
        cityLabel: 'Ciudad',
        stateLabel: 'Estado',
        zipCodeLabel: 'Código postal',
        storyLegend: 'Detalles de la historia',
        storyTitleLabel: 'Título de la historia',
        storyPersonNameLabel: 'Nombre o seudónimo',
        storyLocationLabel: 'Ubicación',
        storySummaryLabel: 'Resumen breve',
        storyBodyLabel: 'Historia completa',
        sending: 'Enviando...',
        sendButton: 'Enviar el envío',
        successMessage: 'Gracias. Hemos recibido tu envío.',
        errorMessage: 'Algo salió mal. Intenta de nuevo más tarde.',
      },
      accessibilityMap: {
        title: 'Mapa de Accesibilidad',
        subtitle: 'Explora recursos y servicios para personas con discapacidad en Bethlehem.',
        backHome: '← Volver al Inicio',
        loading: 'Cargando mapa...',
        mapAriaLabel: 'Mapa interactivo de recursos y problemas de accesibilidad',
        viewDetails: 'Ver detalles',
        showingResource: 'Mostrando ubicación en el mapa para: {{title}}.',
        clearSelection: 'Mostrar todos los recursos',
        showReports: 'Mostrar reportes de ubicaciones inaccesibles',
        showResources: 'Mostrar recursos inmediatos',
        inaccessibleLocationsTitle: 'Ubicaciones Inaccesibles',
        inaccessibleLocationsDescription: 'Este mapa muestra ubicaciones que han sido reportadas como inaccesibles. Ayúdanos a mejorar la accesibilidad reportando problemas que encuentres.',
        reportInaccessibleLocation: 'Reportar Ubicación Inaccesible',
        cancel: 'Cancelar',
        reportAnother: 'Reportar otra ubicación inaccesible',
        reportDetails: 'Detalles del Reporte',
        subjectLabel: 'Asunto',
        detailsLabel: 'Detalles',
        photoLabel: 'Foto (opcional)',
        locationLegend: 'Ubicación',
        enterAddress: 'Ingresar Dirección',
        useCurrentLocation: 'Usar Ubicación Actual',
        streetLabel: 'Calle',
        cityLabel: 'Ciudad',
        stateLabel: 'Estado',
        zipCodeLabel: 'Código Postal',
        contactLegend: 'Información de Contacto (Opcional)',
        nameLabel: 'Nombre',
        emailLabel: 'Correo Electrónico',
        submitReport: 'Enviar Reporte',
        submitting: 'Enviando...',
        successMessage: 'Gracias por tu envío. Revisaremos este reporte y lo publicaremos una vez que haya sido verificado.',
        errorMessage: 'Error al enviar el reporte. Inténtalo de nuevo.',
        accessibleResourcesTitle: 'Recursos Accesibles',
        accessibleResourcesDescription: 'Este mapa muestra ubicaciones de recursos que pueden ayudar con el apoyo a personas con discapacidad y accesibilidad.',
        getCurrentLocation: 'Obtener ubicación actual',
        coordinatesFound: 'Coordenadas encontradas:',
        nearbyAddress: 'Dirección cercana:',
        placePinOnMap: 'Colocar pin en el mapa',
        pinInstructions: 'Haz clic en el mapa arriba para colocar un pin. Puedes arrastrar el pin para ajustar su ubicación.',
      },
    },
    accessibilityPanel: {
      title: 'Opciones de accesibilidad',
      close: 'Cerrar opciones de accesibilidad',
      textSize: 'Tamaño de texto',
      textSizeSmaller: 'Más pequeño',
      textSizeDefault: 'Predeterminado',
      textSizeLarge: 'Grande',
      textSizeXLarge: 'Extra grande',
      colorContrast: 'Contraste de color',
      contrastDefault: 'Predeterminado',
      contrastHigh: 'Alto contraste',
      readingFont: 'Fuente de lectura',
      fontDefault: 'Predeterminado',
      fontDyslexia: 'Amigable con dislexia',
      dyslexiaHint:
        'El modo amigable con dislexia usa una fuente sans-serif limpia con mayor espaciado entre letras y palabras.',
      motionLayout: 'Movimiento y diseño',
      reduceAnimations: 'Reducir animaciones',
      increaseSpacing: 'Aumentar espaciado',
      underlineLinks: 'Subrayar todos los enlaces',
      reset: 'Restablecer toda la accesibilidad',
    },
    breadcrumb: {
      home: 'Inicio',
      resources: 'Recursos inmediatos',
      resource: 'Recurso',
      communityStories: 'Historias de la comunidad',
      story: 'Historia',
      map: 'Mapa de accesibilidad',
      policyGaps: 'Brechas de políticas y servicios',
      disabilityActivism: 'Activismo por la discapacidad',
      submit: 'Enviar un recurso o historia',
      accessibilityStatement: 'Declaración de accesibilidad',
      about: 'Acerca de',
      privacyPolicy: 'Política de privacidad',
      sitemap: 'Mapa del sitio',
      disclaimers: 'Avisos',
    },
    wasThisHelpful: {
      question: '¿Te resultó útil?',
      yes: 'Sí',
      no: 'No',
      thanks: 'Gracias por tus comentarios.',
      foundHelpful: '{{count}} encontraron esto útil',
      didNot: '{{count}} no',
      improveLabel: '¿Cómo podría mejorarse este recurso? (1–2 oraciones requeridas)',
      improvePlaceholder: 'ej., Agregar más opciones de contacto o aclarar los requisitos de elegibilidad…',
      cancel: 'Cancelar',
      submitFeedback: 'Enviar comentarios',
      submitting: 'Enviando…',
      improveError: 'Por favor proporciona 1–2 oraciones sobre cómo podría mejorar este recurso (al menos 20 caracteres).',
      saveError: 'No se pudo guardar tus comentarios. Verifica que VITE_SANITY_TOKEN esté configurado en .env con permisos de escritura.',
      rateAriaLabel: 'Calificar este recurso',
      yesNoAriaLabel: 'Sí o No',
    },
    comments: {
      title: 'Comentarios',
      commentLabelResource: 'Agregar un comentario sobre este recurso',
      commentLabelStory: 'Agregar un comentario sobre esta historia',
      placeholderResource:
        'Comparte tu experiencia con este recurso, haz preguntas o ayuda a otros… (anónimo)',
      placeholderStory: 'Comparte tus pensamientos... (anónimo)',
      placeholderInline: 'Agregar un comentario...',
      charCount: '{{count}} de {{max}} caracteres',
      postComment: 'Publicar comentario',
      posting: 'Publicando...',
      loading: 'Cargando comentarios...',
      noComments: 'Aún no hay comentarios. ¡Sé el primero en compartir!',
      noCommentsInline: 'Sé el primero en comentar',
      anonymous: 'Anónimo',
      flag: 'Reportar comentario',
      flagged: 'Comentario reportado',
      flagCount: '{{count}} reporte(s)',
      commentEmpty: 'El comentario no puede estar vacío',
      loadError: 'No se pudieron cargar los comentarios',
      postError: 'No se pudo publicar el comentario. Intenta de nuevo.',
      postErrorShort: 'No se pudo publicar el comentario',
      flagError: 'No se pudo reportar el comentario',
      alreadyFlagged: 'Ya has reportado este comentario',
      postSuccess: '¡Comentario publicado con éxito!',
      flagSuccess: 'Comentario reportado. Gracias por ayudar a mantener la comunidad segura.',
      rateLimitExceeded:
        'Puedes enviar como máximo {{max}} comentarios por minuto. Espera antes de publicar de nuevo.',
      flagLimitExceeded: 'Has alcanzado el límite diario de reportes. Intenta mañana.',
      commentsOnPassage: 'Comentarios sobre este párrafo',
      closeComments: 'Cerrar comentarios',
      commentOnParagraph: 'Comentar sobre este párrafo',
      paragraph: 'Párrafo:',
      post: 'Publicar',
      inlineCommentsAria: '{{count}} comentarios en línea',
      addInlineCommentAria: 'Agregar comentario en línea',
    },
    footer: {
      navigation: 'Navegación',
      information: 'Información',
      contactUs: 'Contáctanos',
      emailLabel: 'Correo',
      phoneLabel: 'Teléfono',
      addressLabel: 'Dirección',
      aboutBody:
        'El Kit para el bienestar de la discapacidad es una iniciativa comunitaria que apoya a residentes con discapacidad en Bethlehem, PA mediante recursos accesibles y experiencias compartidas.',
      learnMore: 'Conoce más sobre el proyecto',
      copyright:
        '© {{year}} Kit para el bienestar de la discapacidad. Todos los derechos reservados. Creado en colaboración con Lehigh University y la comunidad de Bethlehem.',
    },
  },
}

export function t(lang, key) {
  const parts = key.split('.')
  const get = (obj) => parts.reduce((acc, p) => (acc ? acc[p] : undefined), obj)
  return get(uiStrings[lang]) ?? get(uiStrings.en) ?? key
}

export function tFormat(lang, key, vars = {}) {
  const template = t(lang, key)
  return String(template).replace(/\{\{(\w+)\}\}/g, (_, name) => {
    const value = vars[name]
    return value == null ? '' : String(value)
  })
}

